config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'static_pages#index'
    resources :static_pages,        only: [:index]
    resources :products,            only: [:show]
    resources :categories,          only: [:show]
    resources :orders,              only: [:edit, :update] do
      get     :populate,            on: :collection
      delete  :remove_line_item,    on: :collection
    end
    get '/cart',                    to: 'orders#edit', as: :cart
    get '/delivery_address',        to: 'orders#delivery_address'
    get '/payment',                 to: 'orders#payment'
    get '/confirm',                 to: 'orders#confirm'
    get '/checkout_complete',       to: 'orders#checkout_complete'
    get '/search',                  to: 'products#search'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def related_products(taxons)
    Spree::Product.in_taxons(taxons).
      distinct.
      includes(master: [:default_price, :images]).
      where.not(id: id)
  end

  def self.prepended(base)
    base.scope :search_products, -> (search_params) do
      return if search_params.blank?

      includes(master: [:default_price, :images]).
        where('name LIKE ? OR description LIKE ?', "%#{search_params}%", "%#{search_params}%").
        distinct
    end
  end

  Spree::Product.prepend self
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :option_params, only: :show

  def show
    @taxonomies = Spree::Taxonomy.all.includes(:root)
    @taxon = Spree::Taxon.find(params[:id])
    @products = @taxon.all_products.includes(master: [:default_price, :images])
    @colors = find_option_type('Color')
    @sizes = find_option_type('Size')
    @option_value_color = Spree::OptionValue.find_by(id: @color)
    @option_value_size = Spree::OptionValue.find_by(id: @size)

    if params[:color] || params[:size]
      option_values_variant = Spree::OptionValuesVariant.
        select(:variant_id).
        where("option_value_id IN (?)", (@option_value_color || @option_value_size).id).
        distinct

      @products = @products.
        joins(:variants).
        where(spree_option_values_variants: { variant_id: option_values_variant }).
        includes(:variants, master: [:images, :default_price]).
        eager_load(variants: [:option_values_variants, :prices]).
        order(sort_products(@keyword)).
        distinct
    else
      @products = @products.
        eager_load(variants: [:option_values_variants, :prices]).
        order(sort_products(@keyword))
    end
  end

  private

  def option_params
    @display_type = params[:display_type] == 'list' ? 'list' : 'grid'
    @color        = params[:color]
    @size         = params[:size]
    @keyword      = params[:sort]
  end

  def find_option_type(name)
    if option_type = Spree::OptionType.find_by(name: name) # rubocop:disable Metrics/LineLength, Lint/AssignmentInCondition
      option_type.option_values.includes(:variants)
    end
  end

  def sort_products(keyword)
    case keyword
    when 'new'
      'spree_products.available_on DESC'
    when 'old'
      'spree_products.available_on ASC'
    when 'low'
      'default_prices_spree_variants.amount ASC'
    when 'high'
      'default_prices_spree_variants.amount DESC'
    else
      'spree_products.available_on DESC'
    end
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Auth

  # before_action :check_authorization # orders_specの通過用にコメントアウト
  before_action :assign_order, only: :update
  before_action :get_order, only: :edit
  helper 'spree/products', 'spree/orders'
  respond_to :html

  # Shows the current incomplete order from the session
  def edit
  end

  def update
    authorize! :update, @order

    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_url
  end

  def populate
    @order = current_order(create_order_if_necessary: true)

    variant  = Spree::Variant.find(params[:order][:variant_id])
    quantity = params[:order][:quantity].present? ? params[:order][:quantity].to_i : 1

    @line_item = @order.contents.add(variant, quantity)
    redirect_to potepan_cart_url
  end

  def remove_line_item
    @order = current_order
    line_item = @order.line_items.find(params[:line_item])
    @order.contents.remove_line_item(line_item)
    redirect_to potepan_cart_url
  end

  def delivery_address
  end

  def payment
  end

  def confirm
  end

  def checkout_complete
  end

  private

  def check_authorization
    order = Spree::Order.find_by(number: params[:id]) if params[:id].present?
    order ||= current_order

    if order && action_name.to_sym == :show
      authorize! :show, order, cookies.signed[:token]
    elsif order
      authorize! :edit, order, cookies.signed[:token]
    else
      authorize! :create, Spree::Order
    end
  end

  def order_params
    params.require(:order).permit(line_items_attributes: [:quantity, :id]) # variant_id → id に変更。idはline_itemのidのこと。variant_idを使うとアップデートに失敗し、追加処理になってしまう。 # rubocop:disable Metrics/LineLength
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = Spree.t(:order_not_found)
      redirect_to potepan_url && return
    end
  end

  def get_order
    @order = current_order
    @line_items = @order.line_items.includes(:product, :variant)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_NUMBER_OF_PRODUCT_IMAGES = 4
  MAX_NUMBER_OF_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.available.friendly.find(params[:id])
    @variants = @product.variants_including_master if @product.has_variants?
    @images = @product.variant_images.limit(MAX_NUMBER_OF_PRODUCT_IMAGES)
    taxons = @product.taxons
    if taxons.any?
      @related_products = @product.related_products(taxons).limit(MAX_NUMBER_OF_RELATED_PRODUCTS)
      @taxon = taxons.first
    end
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.
      search_products(@search_word).
      includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/static_pages_controller.rb
class Potepan::StaticPagesController < ApplicationController
  MAX_NUMBER_OF_NEW_PRODUCTS = 6

  def index
    @new_products = Spree::Product.
      where('available_on > ?', Time.zone.now.beginning_of_month). # 当月のリリース商品
      includes(master: [:default_price, :images]).
      order(Spree::Product.arel_table[:available_on].desc).
      limit(MAX_NUMBER_OF_NEW_PRODUCTS)
    @taxon_shirts = Spree::Taxon.find_by(name: "Shirts")
    @taxon_bags = Spree::Taxon.find_by(name: "Bags")
    @taxon_denim = Spree::Taxon.find_by(name: "denim")
  end
end

app/views/potepan/orders/_line_items.html.erb
<%= f.fields_for :line_items, line_item do |field| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to remove_line_item_potepan_orders_path(line_item: line_item.id), method: :delete do %>
        <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <% end %>
        <span class="cartImage"><%= image_tag(line_item.product.display_image.attachment(:small)) %></span>
    </td>
    <td class="col-xs-4"><%= line_item.product.name %></td>
    <td class="col-xs-2"><%= line_item.product.display_price %></td>
    <td class="col-xs-2">
      <%= field.number_field(:quantity, min: 1, max: 99, value: line_item.quantity) %>
    </td>
    <td class="col-xs-2"><%= line_item.display_amount %></td>
  </tr>
<% end %>

app/views/potepan/orders/checkout_complete.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>thanks message</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active">thanks message</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix setp5">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="thanksContent">
          <h2>Thank You !! <small>ご注文ありがとうございます。</small></h2>
          <h3>Shipping Details</h3>
          <div class="thanksInner">
            <div class="row">
              <div class="col-sm-6 col-xs-12 tableBlcok">
                <address>
                  <span>Shipping address:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Email:</span> <a href="mailto:potepan@potepancamp.com">potepan@potepancamp.com</a> <br>
                  <span>Phone:</span> +884 5452 6432
                </address>
              </div>
              <div class="col-sm-6 col-xs-12">
                <div class="well">
                  <h2><small>Order ID</small>9547</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/orders/confirm.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>入力内容確認</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active">入力内容確認</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix stepsWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="innerWrapper clearfix stepsPage">
          <div class="row progress-wizard" style="border-bottom:0;">
            <div class="col-xs-4 progress-wizard-step complete fullBar">
              <div class="text-center progress-wizard-stepnum">お届け先情報</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
            <div class="col-xs-4 progress-wizard-step complete fullBar">
              <div class="text-center progress-wizard-stepnum">お支払い方法</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
            <div class="col-xs-4 progress-wizard-step complete">
              <div class="text-center progress-wizard-stepnum">入力内容確認</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
          </div>
          <form action="" class="row" method="POST" role="form">
            <div class="col-xs-12">
              <div class="page-header">
                <h4>入力内容確認</h4>
              </div>
            </div>
            <div class="col-sm-12 col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">お届け先情報</h4>
                </div>
                <div class="panel-body">
                  <address>
                    <strong>Adam Smith</strong><br>
                    9/4 C Babor Road, Mohammad pur, <br>
                    Shyamoli, Dhaka <br>
                    Bangladesh
                  </address>
                </div>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="cartListInner">
                <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th></th>
                        <th>Product Name</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Sub Total</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td class="col-xs-2">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <span class="cartImage"><%= image_tag("products/cart-image.jpg", :class => "media-left media-object", :alt => "cart-Image") %></span>
                        </td>
                        <td class="col-xs-4">Italian Winter Hat</td>
                        <td class="col-xs-2">$ 99.00</td>
                        <td class="col-xs-2"><input type="text" placeholder="1"></td>
                        <td class="col-xs-2">$ 99.00</td>
                      </tr>
                      <tr>
                        <td class="col-xs-2">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <span class="cartImage"><%= image_tag("products/cart-image.jpg", :class => "media-left media-object", :alt => "cart-Image") %></span>
                        </td>
                        <td class="col-xs-4">Italian Winter Hat</td>
                        <td class="col-xs-2">$ 99.00</td>
                        <td class="col-xs-2"><input type="text" placeholder="1"></td>
                        <td class="col-xs-2">$ 99.00</td>
                      </tr>
                      <tr>
                        <td class="col-xs-2">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          <span class="cartImage"><%= image_tag("products/cart-image.jpg", :class => "media-left media-object", :alt => "cart-Image") %></span>
                        </td>
                        <td class="col-xs-4">Italian Winter Hat</td>
                        <td class="col-xs-2">$ 99.00</td>
                        <td class="col-xs-2"><input type="text" placeholder="1"></td>
                        <td class="col-xs-2">$ 99.00</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="row totalAmountArea">
                  <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                    <ul class="list-unstyled">
                      <li>小計 <span>792円</span></li>
                      <li>消費税 <span>18円</span></li>
                      <li>総計 <span class="grandTotal">810円</span></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="well well-lg clearfix">
                <ul class="pager">
                <li class="previous"><a href="/potepan/payment">戻る</a></li>
                  <li class="next"><a href="checkout_complete">購入確定</a></li>
                </ul>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/orders/delivery_address.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>お届け先情報</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active">お届け先情報</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix stepsWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="innerWrapper clearfix stepsPage">
          <div class="row progress-wizard" style="border-bottom:0;">

            <div class="col-xs-4 progress-wizard-step complete">
              <div class="text-center progress-wizard-stepnum">お届け先情報</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>

            <div class="col-xs-4 progress-wizard-step disabled">
              <div class="text-center progress-wizard-stepnum">お支払い方法</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>

            <div class="col-xs-4 progress-wizard-step disabled">
              <div class="text-center progress-wizard-stepnum">入力内容確認</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
          </div>

          <form action="" class="row" method="POST" role="form">
            <div class="col-xs-12">
              <div class="page-header">
                <h4>入力フォーム</h4>
              </div>
            </div>
            <div class="form-group col-sm-6 col-xs-12">
              <label for="checkout-family-name">姓</label>
              <input type="text" class="form-control" id="checkout-family-name">
            </div>
            <div class="form-group col-sm-6 col-xs-12">
              <label for="checkout-first-name">名</label>
              <input type="text" class="form-control" id="checkout-first-name">
            </div>
            <div class="form-group col-sm-6 col-xs-12">
              <label for="checkout-email">メールアドレス</label>
              <input type="email" class="form-control" id="checkout-email">
            </div>
            <div class="form-group col-sm-6 col-xs-12">
              <label for="checkout-address">住所</label>
              <input type="text" class="form-control" id="checkout-address">
            </div>
            <div class="form-group col-sm-6 col-xs-12">
              <label for="checkout-telephone">電話番号</label>
              <input type="text" class="form-control" id="checkout-telephone">
            </div>
            <div class="col-xs-12">
              <div class="well well-lg clearfix">
                <ul class="pager">
                  <li class="previous"><a href="potepan/orders/cart">戻る</a></li>
                  <li class="next"><a href="/potepan/payment">次へ</a></li>
                </ul>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/orders/edit.html.erb
<% provide(:title, "Cart") %>
<%# LIGHT SECTION %>
<section class="lightSection clearfix pageHeaderImage">
  <div class="container">
    <div class="tableBlock">
      <div class="row tableInner">
        <div class="col-xs-12">
          <div class="page-title">
            <h2>cart</h2>
            <ol class="breadcrumb">
              <li>
                <%= link_to "Home", potepan_path %>
              </li>
              <li class="active">cart</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<%# MAIN CONTENT SECTION %>
<section class="mainContent clearfix cartListWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="cartListInner">
          <%= form_with(model: @order, url: potepan_order_path(@order), method: :patch, local: true) do |f| %>
            <div class="table-responsive">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>商品名</th>
                    <th>価格</th>
                    <th>数</th>
                    <th>小計</th>
                  </tr>
                </thead>
                <tbody>
                  <%= render partial: 'potepan/orders/line_items', collection: @line_items, as: "line_item", locals: { order: @order, f: f } %>
                </tbody>
              </table>
            </div>
            <div class="updateArea">
              <%= f.submit "アップデート", class: "btn" %>
            </div>
            <div class="totalAmountArea">
              <div class="col-sm-4 col-sm-offset-8 col-xs-12">
                <ul class="list-unstyled">
                  <li>小計 <span><%= @order.display_item_total %></span></li>
                  <li>消費税 <span><%= @order.display_tax_total %></span></li>
                  <li>総計 <span class="grandTotal"><%= @order.display_total %></span></li>
                </ul>
              </div>
            </div>
            <div class="checkBtnArea">
              <a href="/potepan/delivery_address" class="btn btn-primary btn-block">購入する<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/orders/payment.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2>お支払い方法</h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li class="active">お支払い方法</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix stepsWrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="innerWrapper clearfix stepsPage">
          <div class="row progress-wizard" style="border-bottom:0;">

            <div class="col-xs-4 progress-wizard-step complete fullBar">
              <div class="text-center progress-wizard-stepnum">お届け先情報</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>

            <div class="col-xs-4 progress-wizard-step active">
              <div class="text-center progress-wizard-stepnum">お支払い方法</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>

            <div class="col-xs-4 progress-wizard-step disabled">
              <div class="text-center progress-wizard-stepnum">入力内容確認</div>
              <div class="progress"><div class="progress-bar"></div></div>
              <i class="progress-wizard-dot"></i>
            </div>
          </div>
          <form action="" class="row" method="POST" role="form">
            <div class="col-xs-12">
              <div class="page-header">
                <h4>お支払い方法</h4>
              </div>
            </div>
            <div class="form-group col-sm-4 col-xs-12">
              <label for="checkout-creditcard-code">カード番号</label>
              <input type="password" class="form-control" id="checkout-card-number">
            </div>
            <div class="form-group col-sm-4 col-xs-12">
              <label for="">有効期限</label>
              <div class="row">
                <div class="col-xs-6">
                  <span class="step-drop">
                    <select name="checkout-card-expiration-month" id="checkout-card-expiration-month" class="select-drop">
                      <option value="1">01</option>
                      <option value="2">02</option>
                      <option value="3">03</option>
                      <option value="4">04</option>
                      <option value="5">05</option>
                      <option value="6">06</option>
                      <option value="7">07</option>
                      <option value="8">08</option>
                      <option value="9">09</option>
                      <option value="10">10</option>
                      <option value="11">11</option>
                      <option value="12">12</option>
                    </select>
                  </span>
                </div>
                <div class="col-xs-6">
                  <span class="step-drop">
                    <select name="checkout-card-expiration-year" id="checkout-card-expiration-year" class="select-drop">
                      <option value="0">2016</option>
                      <option value="1">2017</option>
                      <option value="2">2018</option>
                      <option value="3">2019</option>
                      <option value="4">2020</option>
                      <option value="5">2021</option>
                      <option value="6">2022</option>
                      <option value="7">2023</option>
                      <option value="8">2024</option>
                    </select>
                  </span>
                </div>
              </div>
            </div>
            <div class="form-group col-sm-4 col-xs-12">
              <label for="checkout-card-name">カード名義人</label>
              <input type="text" class="form-control" id="checkout-card-name">
            </div>
            <div class="col-xs-12">
              <div class="well well-lg clearfix">
                <ul class="pager">
                <li class="previous"><a href="/potepan/delivery_address">戻る</a></li>
                  <li class="next"><a href="/potepan/confirm">次へ</a></li>
                </ul>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>