config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'static_pages#index'
    resources :static_pages,        only: [:index]
    resources :products,            only: [:show]
    resources :categories,          only: [:show]
    resources :orders,              only: [:edit, :update] do
      get     :populate,            on: :collection
      delete  :remove_line_item,    on: :collection
    end
    get '/cart',                    to: 'orders#edit', as: :cart
    get '/delivery_address',        to: 'orders#delivery_address'
    get '/payment',                 to: 'orders#payment'
    get '/confirm',                 to: 'orders#confirm'
    get '/checkout_complete',       to: 'orders#checkout_complete'
    get '/search',                  to: 'products#search'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
end

app/models/potepan/product_decorator.rb
module Potepan::ProductDecorator
  def related_products(taxons)
    Spree::Product.in_taxons(taxons).
      distinct.
      includes(master: [:default_price, :images]).
      where.not(id: id)
  end

  def self.prepended(base)
    base.scope :search_products, -> (search_params) do
      return if search_params.blank?

      includes(master: [:default_price, :images]).
        where('name LIKE ? OR description LIKE ?', "%#{search_params}%", "%#{search_params}%").
        distinct
    end
  end

  Spree::Product.prepend self
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  before_action :option_params, only: :show

  def show
    @taxonomies = Spree::Taxonomy.all.includes(:root)
    @taxon = Spree::Taxon.find(params[:id])
    @products = @taxon.all_products.includes(master: [:default_price, :images])
    @colors = find_option_type('Color')
    @sizes = find_option_type('Size')
    @option_value_color = Spree::OptionValue.find_by(id: @color)
    @option_value_size = Spree::OptionValue.find_by(id: @size)

    if params[:color] || params[:size]
      option_values_variant = Spree::OptionValuesVariant.
        select(:variant_id).
        where("option_value_id IN (?)", (@option_value_color || @option_value_size).id).
        distinct

      @products = @products.
        joins(:variants).
        where(spree_option_values_variants: { variant_id: option_values_variant }).
        includes(:variants, master: [:images, :default_price]).
        eager_load(variants: [:option_values_variants, :prices]).
        order(sort_products(@keyword)).
        distinct
    else
      @products = @products.
        eager_load(variants: [:option_values_variants, :prices]).
        order(sort_products(@keyword))
    end
  end

  private

  def option_params
    @display_type = params[:display_type] == 'list' ? 'list' : 'grid'
    @color        = params[:color]
    @size         = params[:size]
    @keyword      = params[:sort]
  end

  def find_option_type(name)
    if option_type = Spree::OptionType.find_by(name: name) # rubocop:disable Metrics/LineLength, Lint/AssignmentInCondition
      option_type.option_values.includes(:variants)
    end
  end

  def sort_products(keyword)
    case keyword
    when 'new'
      'spree_products.available_on DESC'
    when 'old'
      'spree_products.available_on ASC'
    when 'low'
      'default_prices_spree_variants.amount ASC'
    when 'high'
      'default_prices_spree_variants.amount DESC'
    else
      'spree_products.available_on DESC'
    end
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Store
  include Spree::Core::ControllerHelpers::Auth

  # before_action :check_authorization # orders_specの通過用にコメントアウト
  before_action :assign_order, only: :update
  before_action :get_order, only: :edit
  helper 'spree/products', 'spree/orders'
  respond_to :html

  # Shows the current incomplete order from the session
  def edit
  end

  def update
    authorize! :update, @order

    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_url
  end

  def populate
    @order = current_order(create_order_if_necessary: true)

    variant  = Spree::Variant.find(params[:order][:variant_id])
    quantity = params[:order][:quantity].present? ? params[:order][:quantity].to_i : 1

    @line_item = @order.contents.add(variant, quantity)
    redirect_to potepan_cart_url
  end

  def remove_line_item
    @order = current_order
    line_item = @order.line_items.find(params[:line_item])
    @order.contents.remove_line_item(line_item)
    redirect_to potepan_cart_url
  end

  def delivery_address
  end

  def payment
  end

  def confirm
  end

  def checkout_complete
  end

  private

  def check_authorization
    order = Spree::Order.find_by(number: params[:id]) if params[:id].present?
    order ||= current_order

    if order && action_name.to_sym == :show
      authorize! :show, order, cookies.signed[:token]
    elsif order
      authorize! :edit, order, cookies.signed[:token]
    else
      authorize! :create, Spree::Order
    end
  end

  def order_params
    params.require(:order).permit(line_items_attributes: [:quantity, :id]) # variant_id → id に変更。idはline_itemのidのこと。variant_idを使うとアップデートに失敗し、追加処理になってしまう。 # rubocop:disable Metrics/LineLength
  end

  def assign_order
    @order = current_order
    unless @order
      flash[:error] = Spree.t(:order_not_found)
      redirect_to potepan_url && return
    end
  end

  def get_order
    @order = current_order
    @line_items = @order.line_items.includes(:product, :variant)
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_NUMBER_OF_PRODUCT_IMAGES = 4
  MAX_NUMBER_OF_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.available.friendly.find(params[:id])
    @variants = @product.variants_including_master if @product.has_variants?
    @images = @product.variant_images.limit(MAX_NUMBER_OF_PRODUCT_IMAGES)
    taxons = @product.taxons
    if taxons.any?
      @related_products = @product.related_products(taxons).limit(MAX_NUMBER_OF_RELATED_PRODUCTS)
      @taxon = taxons.first
    end
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.
      search_products(@search_word).
      includes(master: [:default_price, :images])
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/controllers/potepan/static_pages_controller.rb
class Potepan::StaticPagesController < ApplicationController
  MAX_NUMBER_OF_NEW_PRODUCTS = 6

  def index
    @new_products = Spree::Product.
      where('available_on > ?', Time.zone.now.beginning_of_month). # 当月のリリース商品
      includes(master: [:default_price, :images]).
      order(Spree::Product.arel_table[:available_on].desc).
      limit(MAX_NUMBER_OF_NEW_PRODUCTS)
    @taxon_shirts = Spree::Taxon.find_by(name: "Shirts")
    @taxon_bags = Spree::Taxon.find_by(name: "Bags")
    @taxon_denim = Spree::Taxon.find_by(name: "denim")
  end
end

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(related_product) do %>
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment(:product), size: "130x130") %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= related_product.name %></h5>
            <h3><%= related_product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/search.html.erb
<% provide(:title, "Results by Search #{@search_word}") %>
<div class="main-wrapper">
  <%# LIGHT SECTION %>
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @search_word %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li><%= link_to "Home", potepan_path %></li>
            <li><%= link_to "shop", '#' %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <%# MAIN CONTENT SECTION %>
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row" id="product_list">
        <% @products.each do |product| %>
          <div class="col-sm-3 col-xs-12">
            <div class="productBox">
              <%= link_to potepan_product_path(product) do %>
                <div class="productImage clearfix">
                  <%= image_tag(product.display_image.attachment(:product)) %>
                </div>
                <div class="productCaption clearfix">
                  <h5><%= product.name %></h5>
                  <h3><%= product.display_price %></h3>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, "Product") %>
<div class="main-wrapper">
  <%# LIGHT SECTION %>
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @product.name %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to "Home", potepan_path %>
            </li>
            <li class="active"><%= @product.name %></li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <%# MAIN CONTENT SECTION %>
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <div class="media-left productSlider">
              <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                  <% @images.each_with_index do |image, index| %>
                    <div class="item <%= "active" if index.zero? %>" data-thumb="<%= index %>">
                      <%= image_tag(image.attachment(:large)) %>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <% @images.each_with_index do |image, index| %>
                      <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb"">
                        <%= image_tag(image.attachment(:small)) %>
                      </div>
                    <% end %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>
            <div class="media-body">
              <% if @taxon %>
                <%= link_to potepan_category_path(@taxon.id) do %>
                  <ul class="list-inline">
                    <li><i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</li>
                  </ul>
                <% end %>
              <% end %>
              <h2><%= @product.name %></h2>
              <h3><%= @product.display_price %></h3>
              <p><%= @product.description.blank? ? "商品説明はありません" : @product.description %></p>
              <%= form_with(scope: :order, url: populate_potepan_orders_path, method: :get, local: true) do |f| %>
                <% if @variants %>
                  <span class="quick-drop">
                    <%= f.select(:variant_id, '', {include_blank: true}, {id: "guiest_id3", class: "select-drop"}) do %>
                      <% @variants.each do |variant| %>
                        <%= content_tag(:option, variant.options_text, value: variant.id) %>
                      <% end %>
                    <% end %>
                  </span>
                <% else %>
                  <span>
                    <%= f.hidden_field(:variant_id, value: @product.master.id) %>
                  </span>
                <% end %>
                <span class="quick-drop resizeWidth">
                  <%= f.select(:quantity, '', {}, {id: "guiest_id4", class: "select-drop"}) do %>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                  <% end %>
                </span>
                <div class="btn-area">
                  <%= f.submit "カートへ入れる", class: "btn btn-primary btn-block" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <%# RELATED PRODUCTS %>
      <% if @related_products %>
        <%= render 'potepan/products/related_products', related_products: @related_products %>
      <% end %>
    </div>
  </section>
</div>