config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'static_pages#index'
    resources :static_pages,        only: [:index]
    resources :products,            only: [:show]
    resources :categories,          only: [:show]
    resources :orders,              only: [:edit, :update] do
      get     :populate,            on: :collection
      delete  :remove_line_item,    on: :collection
    end
    get '/cart',                    to: 'orders#edit', as: :cart
    get '/delivery_address',        to: 'orders#delivery_address'
    get '/payment',                 to: 'orders#payment'
    get '/confirm',                 to: 'orders#confirm'
    get '/checkout_complete',       to: 'orders#checkout_complete'
    get '/search',                  to: 'products#search'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :single_product,            to: 'sample#single_product'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
  end
end

app/views/layouts/_footer.html.erb
<%# FOOTER %>
<%# COPY RIGHT %>
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<%# HEADER %>
<div class="header clearfix">
  <%# TOPBAR %>
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <%= form_with(url: potepan_search_path, method: :get, local: true) do |f| %>
                  <%= f.text_field :search, class: 'form-control', placeholder: 'Search…' %>
                  <%= f.submit "検索", class: 'search-button' %>
                <% end %>
              </ul>
            </li>
            <li class="dropdown">
              <%= link_to potepan_cart_path, class: "dropdown-toggle" do %>
                <i class="fa fa-shopping-cart"></i>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <%# NAVBAR %>
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <%# Brand and toggle get grouped for better mobile display %>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("img/logo.png", :alt => ""), potepan_path, class: "navbar-brand" %>
      </div>
      <%# Collect the nav links, forms, and other content for toggling %>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div><%# /.navbar-collapse %>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'shared/login_modal' %>
    <%= render 'shared/sign_up_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>